/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.avroMode.avro.loja;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

/** Um pedido feito pela loja, com a lista de produtos e método de entrega */
@org.apache.avro.specific.AvroGenerated
public class Pedido extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 113404552833886387L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Pedido\",\"namespace\":\"br.com.avroMode.avro.loja\",\"doc\":\"Um pedido feito pela loja, com a lista de produtos e método de entrega\",\"fields\":[{\"name\":\"codigo_pedido\",\"type\":\"long\"},{\"name\":\"data_pedido\",\"type\":\"long\"},{\"name\":\"tipo_entrega\",\"type\":{\"type\":\"enum\",\"name\":\"TipoEntrega\",\"doc\":\"O tipo de entrega escolhido pelo cliente para o pedido\",\"symbols\":[\"FISICO\",\"DIGITAL\"]}},{\"name\":\"email_cliente\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"endereco_entrega\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Endereco\",\"fields\":[{\"name\":\"logradouro\",\"type\":\"string\"},{\"name\":\"bairro\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"cidade\",\"type\":\"string\"},{\"name\":\"estado\",\"type\":\"string\"},{\"name\":\"CEP\",\"type\":\"string\"},{\"name\":\"telefone\",\"type\":\"string\"}]}],\"default\":null},{\"name\":\"produtos\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ProdutoResumo\",\"fields\":[{\"name\":\"codigo\",\"type\":\"long\"},{\"name\":\"nome\",\"type\":\"string\"},{\"name\":\"preco\",\"type\":\"string\"},{\"name\":\"descricao\",\"type\":[\"null\",\"string\"],\"default\":null}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Pedido> ENCODER =
      new BinaryMessageEncoder<Pedido>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Pedido> DECODER =
      new BinaryMessageDecoder<Pedido>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Pedido> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Pedido> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Pedido> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Pedido>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Pedido to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Pedido from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Pedido instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Pedido fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long codigo_pedido;
   private long data_pedido;
   private br.com.avroMode.avro.loja.TipoEntrega tipo_entrega;
   private java.lang.CharSequence email_cliente;
   private br.com.avroMode.avro.loja.Endereco endereco_entrega;
   private java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> produtos;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Pedido() {}

  /**
   * All-args constructor.
   * @param codigo_pedido The new value for codigo_pedido
   * @param data_pedido The new value for data_pedido
   * @param tipo_entrega The new value for tipo_entrega
   * @param email_cliente The new value for email_cliente
   * @param endereco_entrega The new value for endereco_entrega
   * @param produtos The new value for produtos
   */
  public Pedido(java.lang.Long codigo_pedido, java.lang.Long data_pedido, br.com.avroMode.avro.loja.TipoEntrega tipo_entrega, java.lang.CharSequence email_cliente, br.com.avroMode.avro.loja.Endereco endereco_entrega, java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> produtos) {
    this.codigo_pedido = codigo_pedido;
    this.data_pedido = data_pedido;
    this.tipo_entrega = tipo_entrega;
    this.email_cliente = email_cliente;
    this.endereco_entrega = endereco_entrega;
    this.produtos = produtos;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return codigo_pedido;
    case 1: return data_pedido;
    case 2: return tipo_entrega;
    case 3: return email_cliente;
    case 4: return endereco_entrega;
    case 5: return produtos;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: codigo_pedido = (java.lang.Long)value$; break;
    case 1: data_pedido = (java.lang.Long)value$; break;
    case 2: tipo_entrega = (br.com.avroMode.avro.loja.TipoEntrega)value$; break;
    case 3: email_cliente = (java.lang.CharSequence)value$; break;
    case 4: endereco_entrega = (br.com.avroMode.avro.loja.Endereco)value$; break;
    case 5: produtos = (java.util.List<br.com.avroMode.avro.loja.ProdutoResumo>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'codigo_pedido' field.
   * @return The value of the 'codigo_pedido' field.
   */
  public long getCodigoPedido() {
    return codigo_pedido;
  }


  /**
   * Sets the value of the 'codigo_pedido' field.
   * @param value the value to set.
   */
  public void setCodigoPedido(long value) {
    this.codigo_pedido = value;
  }

  /**
   * Gets the value of the 'data_pedido' field.
   * @return The value of the 'data_pedido' field.
   */
  public long getDataPedido() {
    return data_pedido;
  }


  /**
   * Sets the value of the 'data_pedido' field.
   * @param value the value to set.
   */
  public void setDataPedido(long value) {
    this.data_pedido = value;
  }

  /**
   * Gets the value of the 'tipo_entrega' field.
   * @return The value of the 'tipo_entrega' field.
   */
  public br.com.avroMode.avro.loja.TipoEntrega getTipoEntrega() {
    return tipo_entrega;
  }


  /**
   * Sets the value of the 'tipo_entrega' field.
   * @param value the value to set.
   */
  public void setTipoEntrega(br.com.avroMode.avro.loja.TipoEntrega value) {
    this.tipo_entrega = value;
  }

  /**
   * Gets the value of the 'email_cliente' field.
   * @return The value of the 'email_cliente' field.
   */
  public java.lang.CharSequence getEmailCliente() {
    return email_cliente;
  }


  /**
   * Sets the value of the 'email_cliente' field.
   * @param value the value to set.
   */
  public void setEmailCliente(java.lang.CharSequence value) {
    this.email_cliente = value;
  }

  /**
   * Gets the value of the 'endereco_entrega' field.
   * @return The value of the 'endereco_entrega' field.
   */
  public br.com.avroMode.avro.loja.Endereco getEnderecoEntrega() {
    return endereco_entrega;
  }


  /**
   * Sets the value of the 'endereco_entrega' field.
   * @param value the value to set.
   */
  public void setEnderecoEntrega(br.com.avroMode.avro.loja.Endereco value) {
    this.endereco_entrega = value;
  }

  /**
   * Gets the value of the 'produtos' field.
   * @return The value of the 'produtos' field.
   */
  public java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> getProdutos() {
    return produtos;
  }


  /**
   * Sets the value of the 'produtos' field.
   * @param value the value to set.
   */
  public void setProdutos(java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> value) {
    this.produtos = value;
  }

  /**
   * Creates a new Pedido RecordBuilder.
   * @return A new Pedido RecordBuilder
   */
  public static br.com.avroMode.avro.loja.Pedido.Builder newBuilder() {
    return new br.com.avroMode.avro.loja.Pedido.Builder();
  }

  /**
   * Creates a new Pedido RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Pedido RecordBuilder
   */
  public static br.com.avroMode.avro.loja.Pedido.Builder newBuilder(br.com.avroMode.avro.loja.Pedido.Builder other) {
    if (other == null) {
      return new br.com.avroMode.avro.loja.Pedido.Builder();
    } else {
      return new br.com.avroMode.avro.loja.Pedido.Builder(other);
    }
  }

  /**
   * Creates a new Pedido RecordBuilder by copying an existing Pedido instance.
   * @param other The existing instance to copy.
   * @return A new Pedido RecordBuilder
   */
  public static br.com.avroMode.avro.loja.Pedido.Builder newBuilder(br.com.avroMode.avro.loja.Pedido other) {
    if (other == null) {
      return new br.com.avroMode.avro.loja.Pedido.Builder();
    } else {
      return new br.com.avroMode.avro.loja.Pedido.Builder(other);
    }
  }

  /**
   * RecordBuilder for Pedido instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Pedido>
    implements org.apache.avro.data.RecordBuilder<Pedido> {

    private long codigo_pedido;
    private long data_pedido;
    private br.com.avroMode.avro.loja.TipoEntrega tipo_entrega;
    private java.lang.CharSequence email_cliente;
    private br.com.avroMode.avro.loja.Endereco endereco_entrega;
    private br.com.avroMode.avro.loja.Endereco.Builder endereco_entregaBuilder;
    private java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> produtos;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.avroMode.avro.loja.Pedido.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.codigo_pedido)) {
        this.codigo_pedido = data().deepCopy(fields()[0].schema(), other.codigo_pedido);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.data_pedido)) {
        this.data_pedido = data().deepCopy(fields()[1].schema(), other.data_pedido);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.tipo_entrega)) {
        this.tipo_entrega = data().deepCopy(fields()[2].schema(), other.tipo_entrega);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.email_cliente)) {
        this.email_cliente = data().deepCopy(fields()[3].schema(), other.email_cliente);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.endereco_entrega)) {
        this.endereco_entrega = data().deepCopy(fields()[4].schema(), other.endereco_entrega);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasEnderecoEntregaBuilder()) {
        this.endereco_entregaBuilder = br.com.avroMode.avro.loja.Endereco.newBuilder(other.getEnderecoEntregaBuilder());
      }
      if (isValidValue(fields()[5], other.produtos)) {
        this.produtos = data().deepCopy(fields()[5].schema(), other.produtos);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Pedido instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.avroMode.avro.loja.Pedido other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.codigo_pedido)) {
        this.codigo_pedido = data().deepCopy(fields()[0].schema(), other.codigo_pedido);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.data_pedido)) {
        this.data_pedido = data().deepCopy(fields()[1].schema(), other.data_pedido);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tipo_entrega)) {
        this.tipo_entrega = data().deepCopy(fields()[2].schema(), other.tipo_entrega);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email_cliente)) {
        this.email_cliente = data().deepCopy(fields()[3].schema(), other.email_cliente);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.endereco_entrega)) {
        this.endereco_entrega = data().deepCopy(fields()[4].schema(), other.endereco_entrega);
        fieldSetFlags()[4] = true;
      }
      this.endereco_entregaBuilder = null;
      if (isValidValue(fields()[5], other.produtos)) {
        this.produtos = data().deepCopy(fields()[5].schema(), other.produtos);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'codigo_pedido' field.
      * @return The value.
      */
    public long getCodigoPedido() {
      return codigo_pedido;
    }


    /**
      * Sets the value of the 'codigo_pedido' field.
      * @param value The value of 'codigo_pedido'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder setCodigoPedido(long value) {
      validate(fields()[0], value);
      this.codigo_pedido = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'codigo_pedido' field has been set.
      * @return True if the 'codigo_pedido' field has been set, false otherwise.
      */
    public boolean hasCodigoPedido() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'codigo_pedido' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder clearCodigoPedido() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'data_pedido' field.
      * @return The value.
      */
    public long getDataPedido() {
      return data_pedido;
    }


    /**
      * Sets the value of the 'data_pedido' field.
      * @param value The value of 'data_pedido'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder setDataPedido(long value) {
      validate(fields()[1], value);
      this.data_pedido = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'data_pedido' field has been set.
      * @return True if the 'data_pedido' field has been set, false otherwise.
      */
    public boolean hasDataPedido() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'data_pedido' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder clearDataPedido() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tipo_entrega' field.
      * @return The value.
      */
    public br.com.avroMode.avro.loja.TipoEntrega getTipoEntrega() {
      return tipo_entrega;
    }


    /**
      * Sets the value of the 'tipo_entrega' field.
      * @param value The value of 'tipo_entrega'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder setTipoEntrega(br.com.avroMode.avro.loja.TipoEntrega value) {
      validate(fields()[2], value);
      this.tipo_entrega = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tipo_entrega' field has been set.
      * @return True if the 'tipo_entrega' field has been set, false otherwise.
      */
    public boolean hasTipoEntrega() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tipo_entrega' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder clearTipoEntrega() {
      tipo_entrega = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'email_cliente' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmailCliente() {
      return email_cliente;
    }


    /**
      * Sets the value of the 'email_cliente' field.
      * @param value The value of 'email_cliente'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder setEmailCliente(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.email_cliente = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'email_cliente' field has been set.
      * @return True if the 'email_cliente' field has been set, false otherwise.
      */
    public boolean hasEmailCliente() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'email_cliente' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder clearEmailCliente() {
      email_cliente = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'endereco_entrega' field.
      * @return The value.
      */
    public br.com.avroMode.avro.loja.Endereco getEnderecoEntrega() {
      return endereco_entrega;
    }


    /**
      * Sets the value of the 'endereco_entrega' field.
      * @param value The value of 'endereco_entrega'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder setEnderecoEntrega(br.com.avroMode.avro.loja.Endereco value) {
      validate(fields()[4], value);
      this.endereco_entregaBuilder = null;
      this.endereco_entrega = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'endereco_entrega' field has been set.
      * @return True if the 'endereco_entrega' field has been set, false otherwise.
      */
    public boolean hasEnderecoEntrega() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'endereco_entrega' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public br.com.avroMode.avro.loja.Endereco.Builder getEnderecoEntregaBuilder() {
      if (endereco_entregaBuilder == null) {
        if (hasEnderecoEntrega()) {
          setEnderecoEntregaBuilder(br.com.avroMode.avro.loja.Endereco.newBuilder(endereco_entrega));
        } else {
          setEnderecoEntregaBuilder(br.com.avroMode.avro.loja.Endereco.newBuilder());
        }
      }
      return endereco_entregaBuilder;
    }

    /**
     * Sets the Builder instance for the 'endereco_entrega' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public br.com.avroMode.avro.loja.Pedido.Builder setEnderecoEntregaBuilder(br.com.avroMode.avro.loja.Endereco.Builder value) {
      clearEnderecoEntrega();
      endereco_entregaBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'endereco_entrega' field has an active Builder instance
     * @return True if the 'endereco_entrega' field has an active Builder instance
     */
    public boolean hasEnderecoEntregaBuilder() {
      return endereco_entregaBuilder != null;
    }

    /**
      * Clears the value of the 'endereco_entrega' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder clearEnderecoEntrega() {
      endereco_entrega = null;
      endereco_entregaBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'produtos' field.
      * @return The value.
      */
    public java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> getProdutos() {
      return produtos;
    }


    /**
      * Sets the value of the 'produtos' field.
      * @param value The value of 'produtos'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder setProdutos(java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> value) {
      validate(fields()[5], value);
      this.produtos = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'produtos' field has been set.
      * @return True if the 'produtos' field has been set, false otherwise.
      */
    public boolean hasProdutos() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'produtos' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.Pedido.Builder clearProdutos() {
      produtos = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Pedido build() {
      try {
        Pedido record = new Pedido();
        record.codigo_pedido = fieldSetFlags()[0] ? this.codigo_pedido : (java.lang.Long) defaultValue(fields()[0]);
        record.data_pedido = fieldSetFlags()[1] ? this.data_pedido : (java.lang.Long) defaultValue(fields()[1]);
        record.tipo_entrega = fieldSetFlags()[2] ? this.tipo_entrega : (br.com.avroMode.avro.loja.TipoEntrega) defaultValue(fields()[2]);
        record.email_cliente = fieldSetFlags()[3] ? this.email_cliente : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (endereco_entregaBuilder != null) {
          try {
            record.endereco_entrega = this.endereco_entregaBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("endereco_entrega"));
            throw e;
          }
        } else {
          record.endereco_entrega = fieldSetFlags()[4] ? this.endereco_entrega : (br.com.avroMode.avro.loja.Endereco) defaultValue(fields()[4]);
        }
        record.produtos = fieldSetFlags()[5] ? this.produtos : (java.util.List<br.com.avroMode.avro.loja.ProdutoResumo>) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Pedido>
    WRITER$ = (org.apache.avro.io.DatumWriter<Pedido>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Pedido>
    READER$ = (org.apache.avro.io.DatumReader<Pedido>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.codigo_pedido);

    out.writeLong(this.data_pedido);

    out.writeEnum(this.tipo_entrega.ordinal());

    if (this.email_cliente == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.email_cliente);
    }

    if (this.endereco_entrega == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.endereco_entrega.customEncode(out);
    }

    long size0 = this.produtos.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (br.com.avroMode.avro.loja.ProdutoResumo e0: this.produtos) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.codigo_pedido = in.readLong();

      this.data_pedido = in.readLong();

      this.tipo_entrega = br.com.avroMode.avro.loja.TipoEntrega.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.email_cliente = null;
      } else {
        this.email_cliente = in.readString(this.email_cliente instanceof Utf8 ? (Utf8)this.email_cliente : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.endereco_entrega = null;
      } else {
        if (this.endereco_entrega == null) {
          this.endereco_entrega = new br.com.avroMode.avro.loja.Endereco();
        }
        this.endereco_entrega.customDecode(in);
      }

      long size0 = in.readArrayStart();
      java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> a0 = this.produtos;
      if (a0 == null) {
        a0 = new SpecificData.Array<br.com.avroMode.avro.loja.ProdutoResumo>((int)size0, SCHEMA$.getField("produtos").schema());
        this.produtos = a0;
      } else a0.clear();
      SpecificData.Array<br.com.avroMode.avro.loja.ProdutoResumo> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<br.com.avroMode.avro.loja.ProdutoResumo>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          br.com.avroMode.avro.loja.ProdutoResumo e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new br.com.avroMode.avro.loja.ProdutoResumo();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.codigo_pedido = in.readLong();
          break;

        case 1:
          this.data_pedido = in.readLong();
          break;

        case 2:
          this.tipo_entrega = br.com.avroMode.avro.loja.TipoEntrega.values()[in.readEnum()];
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.email_cliente = null;
          } else {
            this.email_cliente = in.readString(this.email_cliente instanceof Utf8 ? (Utf8)this.email_cliente : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.endereco_entrega = null;
          } else {
            if (this.endereco_entrega == null) {
              this.endereco_entrega = new br.com.avroMode.avro.loja.Endereco();
            }
            this.endereco_entrega.customDecode(in);
          }
          break;

        case 5:
          long size0 = in.readArrayStart();
          java.util.List<br.com.avroMode.avro.loja.ProdutoResumo> a0 = this.produtos;
          if (a0 == null) {
            a0 = new SpecificData.Array<br.com.avroMode.avro.loja.ProdutoResumo>((int)size0, SCHEMA$.getField("produtos").schema());
            this.produtos = a0;
          } else a0.clear();
          SpecificData.Array<br.com.avroMode.avro.loja.ProdutoResumo> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<br.com.avroMode.avro.loja.ProdutoResumo>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              br.com.avroMode.avro.loja.ProdutoResumo e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new br.com.avroMode.avro.loja.ProdutoResumo();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










