/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.avroMode.avro.loja;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class ProdutoResumo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5738325812201398730L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProdutoResumo\",\"namespace\":\"br.com.avroMode.avro.loja\",\"fields\":[{\"name\":\"codigo\",\"type\":\"long\"},{\"name\":\"nome\",\"type\":\"string\"},{\"name\":\"preco\",\"type\":\"string\"},{\"name\":\"descricao\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProdutoResumo> ENCODER =
      new BinaryMessageEncoder<ProdutoResumo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProdutoResumo> DECODER =
      new BinaryMessageDecoder<ProdutoResumo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProdutoResumo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProdutoResumo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProdutoResumo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProdutoResumo>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProdutoResumo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProdutoResumo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProdutoResumo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProdutoResumo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long codigo;
   private java.lang.CharSequence nome;
   private java.lang.CharSequence preco;
   private java.lang.CharSequence descricao;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProdutoResumo() {}

  /**
   * All-args constructor.
   * @param codigo The new value for codigo
   * @param nome The new value for nome
   * @param preco The new value for preco
   * @param descricao The new value for descricao
   */
  public ProdutoResumo(java.lang.Long codigo, java.lang.CharSequence nome, java.lang.CharSequence preco, java.lang.CharSequence descricao) {
    this.codigo = codigo;
    this.nome = nome;
    this.preco = preco;
    this.descricao = descricao;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return codigo;
    case 1: return nome;
    case 2: return preco;
    case 3: return descricao;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.  
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: codigo = (java.lang.Long)value$; break;
    case 1: nome = (java.lang.CharSequence)value$; break;
    case 2: preco = (java.lang.CharSequence)value$; break;
    case 3: descricao = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'codigo' field.
   * @return The value of the 'codigo' field.
   */
  public long getCodigo() {
    return codigo;
  }


  /**
   * Sets the value of the 'codigo' field.
   * @param value the value to set.
   */
  public void setCodigo(long value) {
    this.codigo = value;
  }

  /**
   * Gets the value of the 'nome' field.
   * @return The value of the 'nome' field.
   */
  public java.lang.CharSequence getNome() {
    return nome;
  }


  /**
   * Sets the value of the 'nome' field.
   * @param value the value to set.
   */
  public void setNome(java.lang.CharSequence value) {
    this.nome = value;
  }

  /**
   * Gets the value of the 'preco' field.
   * @return The value of the 'preco' field.
   */
  public java.lang.CharSequence getPreco() {
    return preco;
  }


  /**
   * Sets the value of the 'preco' field.
   * @param value the value to set.
   */
  public void setPreco(java.lang.CharSequence value) {
    this.preco = value;
  }

  /**
   * Gets the value of the 'descricao' field.
   * @return The value of the 'descricao' field.
   */
  public java.lang.CharSequence getDescricao() {
    return descricao;
  }


  /**
   * Sets the value of the 'descricao' field.
   * @param value the value to set.
   */
  public void setDescricao(java.lang.CharSequence value) {
    this.descricao = value;
  }

  /**
   * Creates a new ProdutoResumo RecordBuilder.
   * @return A new ProdutoResumo RecordBuilder
   */
  public static br.com.avroMode.avro.loja.ProdutoResumo.Builder newBuilder() {
    return new br.com.avroMode.avro.loja.ProdutoResumo.Builder();
  }

  /**
   * Creates a new ProdutoResumo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProdutoResumo RecordBuilder
   */
  public static br.com.avroMode.avro.loja.ProdutoResumo.Builder newBuilder(br.com.avroMode.avro.loja.ProdutoResumo.Builder other) {
    if (other == null) {
      return new br.com.avroMode.avro.loja.ProdutoResumo.Builder();
    } else {
      return new br.com.avroMode.avro.loja.ProdutoResumo.Builder(other);
    }
  }

  /**
   * Creates a new ProdutoResumo RecordBuilder by copying an existing ProdutoResumo instance.
   * @param other The existing instance to copy.
   * @return A new ProdutoResumo RecordBuilder
   */
  public static br.com.avroMode.avro.loja.ProdutoResumo.Builder newBuilder(br.com.avroMode.avro.loja.ProdutoResumo other) {
    if (other == null) {
      return new br.com.avroMode.avro.loja.ProdutoResumo.Builder();
    } else {
      return new br.com.avroMode.avro.loja.ProdutoResumo.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProdutoResumo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProdutoResumo>
    implements org.apache.avro.data.RecordBuilder<ProdutoResumo> {

    private long codigo;
    private java.lang.CharSequence nome;
    private java.lang.CharSequence preco;
    private java.lang.CharSequence descricao;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.avroMode.avro.loja.ProdutoResumo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.codigo)) {
        this.codigo = data().deepCopy(fields()[0].schema(), other.codigo);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nome)) {
        this.nome = data().deepCopy(fields()[1].schema(), other.nome);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.preco)) {
        this.preco = data().deepCopy(fields()[2].schema(), other.preco);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.descricao)) {
        this.descricao = data().deepCopy(fields()[3].schema(), other.descricao);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ProdutoResumo instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.avroMode.avro.loja.ProdutoResumo other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.codigo)) {
        this.codigo = data().deepCopy(fields()[0].schema(), other.codigo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nome)) {
        this.nome = data().deepCopy(fields()[1].schema(), other.nome);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.preco)) {
        this.preco = data().deepCopy(fields()[2].schema(), other.preco);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.descricao)) {
        this.descricao = data().deepCopy(fields()[3].schema(), other.descricao);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'codigo' field.
      * @return The value.
      */
    public long getCodigo() {
      return codigo;
    }


    /**
      * Sets the value of the 'codigo' field.
      * @param value The value of 'codigo'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.ProdutoResumo.Builder setCodigo(long value) {
      validate(fields()[0], value);
      this.codigo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'codigo' field has been set.
      * @return True if the 'codigo' field has been set, false otherwise.
      */
    public boolean hasCodigo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'codigo' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.ProdutoResumo.Builder clearCodigo() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nome' field.
      * @return The value.
      */
    public java.lang.CharSequence getNome() {
      return nome;
    }


    /**
      * Sets the value of the 'nome' field.
      * @param value The value of 'nome'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.ProdutoResumo.Builder setNome(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nome = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nome' field has been set.
      * @return True if the 'nome' field has been set, false otherwise.
      */
    public boolean hasNome() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nome' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.ProdutoResumo.Builder clearNome() {
      nome = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'preco' field.
      * @return The value.
      */
    public java.lang.CharSequence getPreco() {
      return preco;
    }


    /**
      * Sets the value of the 'preco' field.
      * @param value The value of 'preco'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.ProdutoResumo.Builder setPreco(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.preco = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'preco' field has been set.
      * @return True if the 'preco' field has been set, false otherwise.
      */
    public boolean hasPreco() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'preco' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.ProdutoResumo.Builder clearPreco() {
      preco = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'descricao' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescricao() {
      return descricao;
    }


    /**
      * Sets the value of the 'descricao' field.
      * @param value The value of 'descricao'.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.ProdutoResumo.Builder setDescricao(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.descricao = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'descricao' field has been set.
      * @return True if the 'descricao' field has been set, false otherwise.
      */
    public boolean hasDescricao() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'descricao' field.
      * @return This builder.
      */
    public br.com.avroMode.avro.loja.ProdutoResumo.Builder clearDescricao() {
      descricao = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override    
    public ProdutoResumo build() {
      try {
        ProdutoResumo record = new ProdutoResumo();
        record.codigo = fieldSetFlags()[0] ? this.codigo : (java.lang.Long) defaultValue(fields()[0]);
        record.nome = fieldSetFlags()[1] ? this.nome : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.preco = fieldSetFlags()[2] ? this.preco : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.descricao = fieldSetFlags()[3] ? this.descricao : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProdutoResumo>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProdutoResumo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProdutoResumo>
    READER$ = (org.apache.avro.io.DatumReader<ProdutoResumo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.codigo);

    out.writeString(this.nome);

    out.writeString(this.preco);

    if (this.descricao == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.descricao);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.codigo = in.readLong();

      this.nome = in.readString(this.nome instanceof Utf8 ? (Utf8)this.nome : null);

      this.preco = in.readString(this.preco instanceof Utf8 ? (Utf8)this.preco : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.descricao = null;
      } else {
        this.descricao = in.readString(this.descricao instanceof Utf8 ? (Utf8)this.descricao : null);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.codigo = in.readLong();
          break;

        case 1:
          this.nome = in.readString(this.nome instanceof Utf8 ? (Utf8)this.nome : null);
          break;

        case 2:
          this.preco = in.readString(this.preco instanceof Utf8 ? (Utf8)this.preco : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.descricao = null;
          } else {
            this.descricao = in.readString(this.descricao instanceof Utf8 ? (Utf8)this.descricao : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










