/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.avroMode.avro.loja;
/** O tipo de entrega escolhido pelo cliente para o pedido */
@org.apache.avro.specific.AvroGenerated
public enum TipoEntrega implements org.apache.avro.generic.GenericEnumSymbol<TipoEntrega> {
  FISICO, DIGITAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TipoEntrega\",\"namespace\":\"br.com.avroMode.avro.loja\",\"doc\":\"O tipo de entrega escolhido pelo cliente para o pedido\",\"symbols\":[\"FISICO\",\"DIGITAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
